name: CI Workflow for Melbin React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Change directory to React app
      run: cd melbin-react-app

    - name: Install dependencies
      run: npm install
      working-directory: melbin-react-app

    - name: Run tests
      run: npm test
      working-directory: melbin-react-app

    - name: Build project
      run: npm run build
      working-directory: melbin-react-app
